### ISSUE TITLE
Overview of LCP should be reviewed 

### ISSUE THREAD

**Issue by rkwright** [readium/readium.github.io#20]
The writeup of Readium LCP is probably somewhat dated now.  Should be reviewed by Dan and/or Laurent.

**Comment by danielweck** [comment]
Right now in this repository:

http://readium.org/technical/readium-lcp-specification/
=>
https://github.com/readium/readium.github.io/blob/master/_pages/technical/lcp-specification.md

http://readium.org/technical/readium-lsd-specification/
=>
https://github.com/readium/readium.github.io/blob/master/_pages/technical/lsd-specification.md

http://readium.org/technical/readium-lcp-specs-codebase/
=>
https://github.com/readium/readium.github.io/blob/master/_pages/technical/lcp-specs-codebase.md

The EDRLab intro docs for LCP are pretty good (and reference the above):
https://www.edrlab.org/readium/readium-lcp/

...however, readium.org also has its own intro doc:

http://readium.org/development/readium-lcp-overview/
=>
https://github.com/readium/readium.github.io/blob/master/_pages/development/readium-lcp-overview.md

So @llemeurfr , should the LCP intro doc hosted at readium.org contain no text, just a redirect to the most up-to-date / thorough info at EDRLab? Only the 3 aforementioned "spec" docs would remain hosted at readium.org

**Comment by llemeurfr** [comment]
IMO the readium page should contain an introduction, before linking to the EDRLab pages which contain evolving info with many details. 

This intro should contain info on the inception of the project (initiated by the IDPF - moved to Readium Foundation for the spec - EDRLab for the management of the DRM), plus links to the specification (2 links) and a link to EDRLab/LCP.

Would you like to have something else in this intro?

**Comment by danielweck** [comment]
I personally think there is too much detailed (technical) information in the readium.org "landing page", in the long run it would be better to have a short intro about the history and motivations (with links to the IDPF white paper, spec docs hosted at readium.org, and EDRLab for further deeper tech info).

**Comment by rkwright** [comment]
@danielweck @llemeurfr 
I am with Daniel here.  The info on readium.org should be teasers, leading to more detailed info elsewhere.
But more generally, I think we need to take a step back and think about the whole site, what we're trying to achieve, etc.  That seems like a Communication TF area, but the TF seems unlikely to do much before September.

**Comment by llemeurfr** [comment]
I have mostly re-written this page and think we can close this issue.
