### ISSUE TITLE
Releases page needs work

### ISSUE THREAD

**Issue by rkwright** [readium/readium.github.io#21]
[Releases page](http://readium.org/development/releases/) only references Readium 1 - not any of the R2 or LCP releases.  

Also the various release paragraphs don't have links to the actual release notes.

**Comment by HadrienGardeur** [comment]
I think it's going to be difficult to track releases for R2 projects since everything is spread across various platforms and repos.

**Comment by rkwright** [comment]
True, but doesn't mean it isn't worth doing.  In any case, I will move the old releases page to a wiki page so we don't lose the information if we don't have it on the main page anymore.
