### ISSUE TITLE
"Organizational Documents" may be out of date

### ISSUE THREAD

**Issue by rkwright** [readium/readium.github.io#29]
The ["Organizational Documents" page](http://readium.org/membership/organization/) lists three documents (Bylaws, Certificate of Incorporation, the ICLA).  

- Do any of these need to be updated?  
- Are there additional docs that should be there?

**Comment by HadrienGardeur** [comment]
It's worse than that, the links are all dead and I don't think we have them on our repo.

**Comment by rkwright** [comment]
@HadrienGardeur I see it.  This page got overlooked.  I'll fix it.

**Comment by HadrienGardeur** [comment]
I don't think that it is worth restoring a full page just for that, IMO it
is much better to have less pages that are a little more content rich.

That's what I've done with the overview page in membership for example.
