### ISSUE TITLE
Link issue in the LCP page

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium.github.io#39]
The links to the LCP and LSD specs are re-written somewhere and work. e.g. The [LCP specification](/technical/readium-lcp-specification/) becomes http://readium.org/technical/readium-lcp-specification/.

The information which links to the specs should be clearer. 

The link to the Readium LCP Specs and Codebase is broken: [Readium LCP Specs and Codebase](/technical/lcp-specs-codebase/) but te .md file is indeed there. Is it because of a redirection?

**Comment by rkwright** [comment]
Both of the above links reference github.com, not readium.github.com:

https://github.com/technical/readium-lcp-specification/
https://github.com/technical/lcp-specs-codebase/

**Comment by llemeurfr** [comment]
Issue found, the permalink in lcp-specs-codebase.md was not set correctly. Now set to /technical/readium-lcp-specs-codebase/.

Corrected in 477a8906ea2e3b0514f6d4ebf9669280c5d55f6a
