### ISSUE TITLE
Link broken for webpub manifest definitions

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium.github.io#40]
In https://github.com/readium/webpub-manifest#metadata,
the link to http://readium.org/webpub/default.jsonld is broken. 
same for http://readium.org/webpub/default.jsonld
and http://readium.org/webpub/epub.jsonld

**Comment by rkwright** [comment]
@llemeurfr The report above lists two links but they appear to be the same.  Is that a typo?  And the file default.jsonld  can't be found.  I see two jsonld files, epub/context.jsonld and default/context.jsonld.  I went way back in time looking for the default.jsonld file and cannot find it.

**Comment by llemeurfr** [comment]
@HadrienGardeur, looking at the repo it appears that the stable URLs of the jsonld schemas should be

 http://readium.org/webpub-manifest/contexts/default/context.jsonld
and
 http://readium.org/webpub-manifest/contexts/epub/context.jsonld

Please advise if this is not the case.

**Comment by llemeurfr** [comment]
An issue about this was already open as https://github.com/readium/webpub-manifest/issues/3.
Hadrien was asking for a redirect from the "official" URL to the "physical" one. Let's close this issue and finalize the discussion in the webpub-manifest repo.
