### ISSUE TITLE
EPUB Zone

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium.github.io#41]
Do we really need an EPUB Zone in our main menu?

The links are not necessarily up to date (3.2 just got released) and I'm not sure that this is bringing a lot of value to our current website.

cc @llemeurfr @rkwright

**Comment by rkwright** [comment]
@HadrienGardeur   I agree that it possibly doesn't merit a main menu item, but it seems like a very useful page to have.  Agreed that the links need to be updated, but a lot of less sophisticated folks may  have some trouble navigating the web of specs associated with EPUB.

**Comment by llemeurfr** [comment]
It was also in my mind that EPUB Zone does not need to be in the menu. EPUB Secret has more up to date info, and Medium main gain traction for instance. On the EDRLab website I keep a menu entry about EPUB, with an introduction and links. We could do the equivalent on the readium website, linking to this page from the home page (a block to add).

**Comment by HadrienGardeur** [comment]
We already have a link to the EPUB Zone section of the Readium website, it's the EPUB logo and it points to https://readium.org/epub_zone/resources/

In terms of link/visibility, this is probably good enough, but we probably want to update that page and/or point to a different one.

**Comment by rkwright** [comment]
Cleaned up the links and removed obsolete verbiage.  Commit is https://github.com/readium/readium.github.io/commit/a70cfd56b5b2bb413d89ba67e083ab618a07d790
