### ISSUE TITLE
Update list of current members

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium.github.io#42]
There's an improved version of the membership overview page that displays the list of current members using a list instead of a huge blob of text.

I don't think that this list is up to date though.

@rkwright could you coordinate with Bente and Micah to remove inactive members from that list ?

**Comment by rkwright** [comment]
@HadrienGardeur OK, but it seems this issue is essentially a duplicate of issue #27

**Comment by HadrienGardeur** [comment]
Yeah, sorry about this, I'm going to close this one.
